### ISSUE TITLE
Inline Documentation not showing

### ISSUE THREAD

**Issue by ryanalbrecht** [jcberquist/sublimetext-cfml#111]
Hi, 

For some reason my inline documentation is not working.  I am getting the following error in the console.

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "src.inline_documentation in C:\Users\ryan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 172, in run
  File "src.inline_documentation in C:\Users\ryan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 140, in display_documentation
  File "src.inline_documentation in C:\Users\ryan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 109, in generate_documentation
  File "src.minihtml in C:\Users\ryan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 150, in get_selector_style_map
  File "src.minihtml in C:\Users\ryan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 179, in get_color_scheme
KeyError: 'foreground'`

**Comment by jcberquist** [comment]
What version of ST are you on, and what color scheme are you using?

**Comment by ryanalbrecht** [comment]
Hey jcberquist.

Ok so it looks like the problem is happening when I use the color scheme 'Afterglow twilight' from the _https://github.com/YabataDesign/afterglow-theme_ theme 

This could also be the specific file https://github.com/YabataDesign/afterglow-theme/blob/master/Afterglow-twilight.tmTheme. Unfortunately I am unsure how sublime work with color schemes

**Comment by jcberquist** [comment]
Thanks! that is very helpful. Looks like the issue comes here: https://github.com/YabataDesign/afterglow-theme/blob/master/Afterglow-twilight.tmTheme#L154-L159. I made some assumptions about the structure of `tmTheme` files that aren't quite right, I think I can add an extra check to avoid this error.

**Comment by ryanalbrecht** [comment]
Great stuff! Thanks for all your effort you put into this package!
