### ISSUE TITLE
ST4 & close tags

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#131]
Hi,
I am trying sublimetext 4 (DEV) and i have the following problem:

in the `.cfm` files when I try to close a tag, eg `<cfif q.recordcount` does not insert the close `>` when I press the key on the keyboard.

I'm not sure I explained myself...

This is what I found in the console, if it helps:

```log

reloading python 3.3 plugin CFML.cfml_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 297, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1574, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/ionut/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package/cfml_plugin.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1574, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Applications/Sublime Text.app/Contents/MacOS/Packages/HTML.sublime-package/html_completions.py", line 293
    details=f'Renders as <code>{printed}</code>',
                                               ^
SyntaxError: invalid syntax
reloading python 3.3 plugin CFMLDocPlugin.docifycfml

```

**Comment by jcberquist** [comment]
The plugin doesn't work as is on ST4. I do have a ST4 branch working for me locally. I will have to look into whether it is possible to support both versions, depending on whether ST3 or ST4 is installing it.

**Comment by ivanionut** [comment]
Hi @jcberquist and thanks so much for the support!
Hope to have good news regarding ST4 support 😃 

Thanks again,
Ivan

**Comment by jcberquist** [comment]
I have updated the repo and the the entry on Package Control, ST4 should now get an up to date version of `CFML` that works with it.

**Comment by ivanionut** [comment]
wow, great! I really thank you for your contribution! 👏
