### ISSUE TITLE
Errors happening, no internet connection

### ISSUE THREAD

**Issue by dogsoldier68** [jcberquist/sublimetext-cfml#72]
Using Build 3126 - I have no internet connection, however these just keep happening, any ideas?

I keep getting these errors like every 10 or 20 seconds and the whole thing locks up:

File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\CFML\src\inline_documentation.py", line 132, in run
    docs = get_inline_documentation(cfml_view, doc_type)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\CFML\src\inline_documentation.py", line 25, in get_inline_documentation
    inline_doc = callback(cfml_view, doc_type)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\CFML\src\cfdocs\cfdocs.py", line 67, in get_inline_documentation
    data, success = get_cfdoc(doc_name)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\CFML\src\cfdocs\cfdocs.py", line 95, in get_cfdoc
    return fetch_cfdoc(function_or_tag)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\CFML\src\cfdocs\cfdocs.py", line 134, in fetch_cfdoc
    json_string = urllib.request.urlopen(full_url).read().decode("utf-8")
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1289, in https_open
  File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Unable to fetch update url contents
Traceback (most recent call last):
  File "./python3.3/urllib/request.py", line 1248, in do_open
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 1198, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by jcberquist** [comment]
Sorry again! This is because by default this package attempts to load [cfdocs.org](https://cfdocs.org) data from GitHub. It uses this data to provide documentation for builtin functions and tags. Unfortunately I don't currently have a way to turn this off entirely. However it is possible to clone the cfdocs.org repo from GitHub to local disk and point the plugin to the local installation folder. Is that something that would work for you?

See this section https://github.com/jcberquist/sublimetext-cfml#inline-documentation - basically you would need to git clone https://github.com/foundeo/cfdocs to your local disk and then use <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> to open the command palette and find and select `CFML: Settings - User`. Then you add the setting `cfdocs_path` to it with the path to the data directory of cfdocs repo specified, e.g.:
```
"cfdocs_path": "C:/github/cfdocs/data/en/"
```
After you save, it should stop trying to access the GitHub repo via the internet.

**Comment by jcberquist** [comment]
I was thinking about this a bit more, and I think it is likely that these errors are happening when you are hovering the mouse over builtin functions and tags. So another option you have is to disable this behavior by setting `"cfml_hover_docs": false` in your user package settings. (The same place the `cfdocs_path` setting would go.) With that set to false, the only time the plugin would attempt to load cfdocs data from the internet is when you press <kbd>F1</kbd> while the cursor is on a function or tag (which you could obviously avoid doing).

Still, if possible, I think it would be preferable to have a local copy of the cfdocs data.

**Comment by dogsoldier68** [comment]
It worked!!

Thank you for all the help.
