### ISSUE TITLE
Inline docs no longer displaying on mouse hover.

### ISSUE THREAD

**Issue by patosullivan** [jcberquist/sublimetext-cfml#95]
Sublime Text 3 build 3134.

Installed CFML via Package Control today. No other packages installed.

Any time I hover over a CFML tag the console displays this error:

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "src.inline_documentation in C:\Users\posullivan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 168, in run
  File "src.inline_documentation in C:\Users\posullivan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 45, in get_inline_documentation
  File "src.cfdocs.cfdocs in C:\Users\posullivan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 78, in get_inline_documentation
  File "src.cfdocs.cfdocs in C:\Users\posullivan\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package", line 172, in build_cfdoc
KeyError: 'returns'`

**Comment by jcberquist** [comment]
Hover documentation loads from the cfdocs repository on Github by default - it looks like this commit today https://github.com/foundeo/cfdocs/commit/3bc15776743edb5eddea79db7a11e2320e08fe65 broke things for me since the `returns` key no longer exists for tags. I will get a fix out as soon as I can.

**Comment by patosullivan** [comment]
Thanks, that was super fast. Really appreciate your work!

**Comment by jcberquist** [comment]
Thank you! I drafted a new release so that Package Control would pick up the fix, but since it checks packages once every 1-2 hours, it might still be a while till this fix shows up.
